title: "Dr. Tara P Mishra — Project Scientist, Molecular Foundry"
description: "Advanced Electron Microscopy · Autonomous Characterization · Energy Materials"
baseurl: ""
url: "https://quantumstud.github.io"

theme: minima

author:
  name: "Dr. Tara P Mishra"
  email: tpmishra@lbl.gov
  scholar: https://scholar.google.com/citations?user=vtbEcEsAAAAJ&hl=en
  orcid: https://orcid.org/0000-0002-3000-2555
  github: https://github.com/Quantumstud

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

header_pages:
  - about.md
  - projects.md
  - publications.md
  - news.md
